environment:
  nodejs_version: "6"
  
# Install NodeJS on Windows and install dependencies
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gulp

# Build and run unit tests and a subgroup of the E2E tests
test_script:
  - node --version
  - npm --version
  - npm run test
  - npm run e2e-test